---
- name: Deploy and execute SAP Instances script
  hosts: "{{ target_hosts }}"
  become: true
  vars:
    command: ""
    SID: ""
  tasks:
    - name: Execute SAP Instances script
      script:
         cmd: /data/ansible-data/customer-data/scripts/sap_instances.sh {{ command | default('') }} {{ SID | default('all') }}
      register: script_output
    - name: Display script output
      debug:
        var: script_output.stdout_lines
      when: script_output.stdout_lines is defined